spring:
  application:
    name: TeamWorkApi
  datasource:
    url: jdbc:mysql://localhost:3306/twApi_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.steverado.TeamWorkApi: DEBUG
    org:
      springframework:
        security: DEBUG

        logging:
          level:
            root: INFO
            com.steverado.TeamWorkApi: DEBUG

cloud_name: ${CLOUD_NAME}
api_key: ${API_KEY}
api_secret: ${API_SECRET}



